version: '3'
services:
  app:  # Changed from "web" to "app"
    build: .
    command: uvicorn app.api:app --host 0.0.0.0 --port 8000
    enviroment:
      - DATABASE_URL postgresql://user:db123@host.docker.internal:10000/bookswap
      - SECRET_KEY = 09d25e094faa6ca2556c818166b7a9563b93f7099f6f0f4caa6cf63b88e8d3e7
      - ALGORITHM = HS256
      - ACCESS_TOKEN_EXPIRE_MINUTES = 30
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: bookswap
      POSTGRES_USER: user
      POSTGRES_PASSWORD: db123
    ports:
      - "10000:5432"

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    restart: always
    environment:
      - PGADMIN_DEFAULT_EMAIL=pgadmin4@pgadmin.org
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - "5050:80"
    depends_on:
      - db
  
